version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile-frontend  # Ensure this file exists in the public directory
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Ensure this file exists in the backend directory
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development