"""Menambahkan Table ShoeRecomendationForUser dan Routes nya

Revision ID: 56a17b17e247
Revises: 611cf36c56ce
Create Date: 2024-11-08 02:16:12.872237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a17b17e247'
down_revision = '611cf36c56ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoe_recomendation_for_users',
    sa.Column('id_shoe_recomendation', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('shoe_detail_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['shoe_detail_id'], ['shoe_detail.shoe_detail_id'], ),
    sa.PrimaryKeyConstraint('id_shoe_recomendation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoe_recomendation_for_users')
    # ### end Alembic commands ###
