"""Delete Wallet and Discount

Revision ID: 5e369b8c6b3b
Revises: 4f616fe0d764
Create Date: 2024-10-28 00:38:15.106376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e369b8c6b3b'
down_revision = '4f616fe0d764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.drop_table('discount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
    sa.Column('id_discount', sa.INTEGER(), nullable=False),
    sa.Column('shoe_detail_id', sa.INTEGER(), nullable=False),
    sa.Column('discount_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('discount_value', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('expiration_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['shoe_detail_id'], ['shoe_detail.shoe_detail_id'], ),
    sa.PrimaryKeyConstraint('id_discount'),
    sa.UniqueConstraint('discount_code')
    )
    op.create_table('wallet',
    sa.Column('id_wallet', sa.INTEGER(), nullable=False),
    sa.Column('id_user', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id_wallet')
    )
    # ### end Alembic commands ###
