"""Remove Gallery From Database

Revision ID: 611cf36c56ce
Revises: 5e369b8c6b3b
Create Date: 2024-10-31 19:47:52.117123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611cf36c56ce'
down_revision = '5e369b8c6b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('gallery_id', sa.INTEGER(), nullable=False),
    sa.Column('shoe_detail_id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['shoe_detail_id'], ['shoe_detail.shoe_detail_id'], ),
    sa.PrimaryKeyConstraint('gallery_id')
    )
    # ### end Alembic commands ###
